motion.max_linear_velocity: 0.1  # Maximum linear velocity for trajectory generation (m/s) [0.0, 3.0]
motion.max_angular_velocity: 1.0  # Maximum angular velocity for trajectory generation (rad/s) [0.0, 2.5]

filter.target_pose: 1.0  # Smoothing for single-pose inputs using EMA (0.0: Max filtering, 1.0: No filtering)

log.enabled: true
log.robot_state: false  #  ee position, velocity, joint states, ...
log.targets: false  # target pose
log.timing: true

